--liquibase formatted sql

--changeset vetyutnev:001-create-notification-tables

CREATE TABLE notification_event_payloads (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             message_id UUID NOT NULL UNIQUE,
                                             event_type VARCHAR(50) NOT NULL,
                                             event_id BIGINT NOT NULL,
                                             occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                             changed_by_id BIGINT,
                                             owner_id BIGINT NOT NULL,
                                             event_name VARCHAR(255) NOT NULL,
                                             payload_json JSONB NOT NULL
);

CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               payload_id BIGINT NOT NULL,
                               is_read BOOLEAN NOT NULL DEFAULT FALSE,
                               created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               read_at TIMESTAMP WITH TIME ZONE,

                               CONSTRAINT fk_notification_payload FOREIGN KEY (payload_id) REFERENCES notification_event_payloads(id) ON DELETE CASCADE
);

--rollback DROP TABLE notifications;
--rollback DROP TABLE notification_event_payloads;