spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_manager
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none

jwt:с
  secret: ${JWT_SECRET:YmFzZTY0LWVuY29kZWQtc2VjcmV0LWtleS1tdXN0LWJlLWF0LWxlYXN0LTMyLWJ5dGVzLWxvbmc=}
  ttl-millis: ${JWT_TTL:86400000}