--liquibase formatted sql

--changeset vetyutnev:003-create-user-table
CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    age INT NOT NULL CHECK (age >= 0),
    role VARCHAR(50) NOT NULL
);

--rollback DROP TABLE user_account;