--liquibase formatted sql

--changeset vetyutnev:004-create-events-and-registrations

CREATE TABLE event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner_id BIGINT NOT NULL,
    max_places INT NOT NULL CHECK (max_places >= 1),
    occupied_places INT NOT NULL DEFAULT 0 CHECK (occupied_places >= 0 AND occupied_places <= max_places),
    date TIMESTAMP NOT NULL,
    cost INT NOT NULL CHECK (cost > 0),
    duration INT NOT NULL CHECK (duration > 0),
    location_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,

    CONSTRAINT fk_event_owner FOREIGN KEY (owner_id) REFERENCES user_account(id),
    CONSTRAINT fk_event_location FOREIGN KEY (location_id) REFERENCES location(id)
);


CREATE TABLE registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_event_user UNIQUE (event_id, user_id),

    CONSTRAINT fk_registration_event FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE,
    CONSTRAINT fk_registration_user FOREIGN KEY (user_id) REFERENCES user_account(id)
);

--rollback DROP TABLE registration;
--rollback DROP TABLE event;