--liquibase formatted sql

--changeset vetyutnev:001-create-location-table
CREATE TABLE location (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          address VARCHAR(255) NOT NULL,
                          capacity INT NOT NULL
);

--rollback DROP TABLE location;