--liquibase formatted sql

--changeset vetyutnev:006-create-outbox

CREATE TABLE outbox_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_outbox_status ON outbox_messages(status);

--rollback DROP TABLE outbox_messages;